server:
  port: 6688
  
spring:
  application:
    name: ms-sidecar-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/
  instance:
    prefer-ip-address: true
    